version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    environment:
      - xpack.security.enabled=false  # disable security
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - elastic_vol:/user/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic
    restart: always
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.1
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elasticsearch
    restart: always

networks:
  elastic:
    driver: bridge

volumes:
  elastic_vol:
